plugins:
  sonar-java:
    enabled: true
  checkstyle:
    enabled: true
  stylelint:
    enabled: true  
  eslint:
    enabled: true
  tslint:
    enabled: true
    config: tsconfig.json
