version: 3

project:
  name: "tech-demo-test"
  id: "custom+46919/github.com/Foundation-s-r-o/tech-demo-test"

analyze:
  modules:
    - name: "react-bootstrap"
      type: "npm"
      target: "ui"
      options:
        allow-npm-err: true
      policy:
        license:
          allow:
            - "MIT"
          disallow: []
          unresolved: "warn"
    - name: "tech-demo-api"
      type: "maven"
      target: "api/pom.xml"
      policy:
        license:
          allow:
            - "MIT"
            - "Apache-2.0"
            - "EPL-2.0"
            - "LGPL-2.1-only"
            - "LGPL-2.1-or-later"
            - "GPL-2.0-with-classpath-exception"
          disallow: []
          unresolved: "warn"