-- Portable ANSI DDL (no MySQL/H2-isms) so the future H2 -> PostgreSQL switch is a non-event.
create table PERSON (
	ID bigint generated by default as identity primary key,
	FIRST_NAME varchar(255) not null,
	LAST_NAME varchar(255) not null,
	EMAIL varchar(255) not null,
	ADDRESS varchar(255),
	STATE varchar(255),
	PHONE_NUMBER varchar(255)
);

create index IDX_LN_FN on PERSON (LAST_NAME, FIRST_NAME);

alter table PERSON add constraint UK_EMAIL unique (EMAIL);
