-- Application users for simple DB-backed login. Portable ANSI DDL.
-- Table named USERS (USER is a reserved word in several databases).
create table USERS (
	ID bigint generated by default as identity primary key,
	USERNAME varchar(255) not null,
	PASSWORD varchar(255) not null,
	FIRST_NAME varchar(255),
	LAST_NAME varchar(255),
	ROLE varchar(64) not null,
	ENABLED boolean not null
);

alter table USERS add constraint UK_USERNAME unique (USERNAME);
