name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
        cache-dependency-path: './ui/package-lock.json'
    - run: | 
        npm ci
        npm run build --if-present
      
