name: Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag docker image'
        default: "latest"
      git-ref:
        description: 'The branch, tag or SHA to checkout'
        default: "master"

jobs:
  
  build:
    name: Build Image
    runs-on: ubuntu-latest
   
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with: 
        ref:  ${{ github.event.inputs.git-ref }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to AWS ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ADMIN_PASSWORD : ${{ secrets.ADMIN_PASSWORD }}
        IMAGE_TAG:  ${{ github.event.inputs.tag }}
        DOCKER_BUILDKIT: 1
      run: |
        docker build -t $ECR_REGISTRY/foundation/tech-demo-api:$IMAGE_TAG --build-arg ADMIN_USERNAME=admin --build-arg ADMIN_PASS=$ADMIN_PASSWORD .
        docker push $ECR_REGISTRY/foundation/tech-demo-api:$IMAGE_TAG
